DEBUG

(node:16112) UnhandledPromiseRejectionWarning: SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`database1`.`playerMatches`, CONSTRAINT `playerMatches_ibfk_2` FOREIGN KEY (`uid`) REFERENCES `users` (`uid`))
    at Query.formatError (C:\Users\Petter\Documents\GitHub\inhouseBot\node_modules\sequelize\lib\dialects\mysql\query.js:236:16)
    at Query.handler [as onResult] (C:\Users\Petter\Documents\GitHub\inhouseBot\node_modules\sequelize\lib\dialects\mysql\query.js:68:23)
    at Query.execute (C:\Users\Petter\Documents\GitHub\inhouseBot\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (C:\Users\Petter\Documents\GitHub\inhouseBot\node_modules\mysql2\lib\connection.js:408:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (C:\Users\Petter\Documents\GitHub\inhouseBot\node_modules\mysql2\lib\connection.js:70:12)
    at PacketParser.executeStart (C:\Users\Petter\Documents\GitHub\inhouseBot\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (C:\Users\Petter\Documents\GitHub\inhouseBot\node_modules\mysql2\lib\connection.js:77:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
(node:16112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)

Morgelev #4174
2475
mid 15 1 -25 





<--- Last few GCs --->

[7909:0x4caa0c0] 3595007992 ms: Mark-sweep 471.2 (499.0) -> 470.1 (499.0) MB, 678.9 / 0.0 ms  (average mu = 0.946, current mu = 0.941) allocation failure scavenge might not succeed
[7909:0x4caa0c0] 3595021185 ms: Mark-sweep 471.1 (499.0) -> 470.1 (499.2) MB, 792.8 / 0.0 ms  (average mu = 0.943, current mu = 0.940) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb12b40 node::Abort() [node]
 2: 0xa2fe25 node::FatalError(char const*, char const*) [node]
 3: 0xcf946e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcf97e7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xee3875  [node]
 6: 0xef25f1 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xef584c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0xec1dfb v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
 9: 0x122adbb v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
10: 0x160c599  [node]
Aborted (core dumped)